CREATE SCHEMA SOCIAL_NETWORK;

CREATE TABLE SOCIAL_NETWORK.USER (
    USER_ID INTEGER PRIMARY KEY,
    USER_NM VARCHAR(255) NOT NULL,
    DESCRIPTION_TXT TEXT,
    PATH_TO_PHOTO_TXT VARCHAR(255),
    VALID_FROM_DTTM TIMESTAMP DEFAULT now(),
    VALID_TO_DTTM TIMESTAMP DEFAULT now() + interval '100 year'
);

CREATE TABLE SOCIAL_NETWORK.POST (
    POST_ID INTEGER PRIMARY KEY,
    AUTHOR_ID INTEGER REFERENCES SOCIAL_NETWORK.USER(USER_ID) NOT NULL,
    POST_TXT TEXT,
    POST_DTTM TIMESTAMP DEFAULT now()
);

CREATE TABLE SOCIAL_NETWORK.LIKED_POSTS (
    POST_ID INTEGER REFERENCES SOCIAL_NETWORK.POST(POST_ID) NOT NULL ,
    USER_ID INTEGER REFERENCES SOCIAL_NETWORK.USER(USER_ID) NOT NULL,
    CONSTRAINT PAIR_KEY PRIMARY KEY(POST_ID, USER_ID)
);

CREATE TABLE SOCIAL_NETWORK.COMMENT (
    COMMENT_ID INTEGER PRIMARY KEY ,
    AUTHOR_ID INTEGER REFERENCES SOCIAL_NETWORK.USER(USER_ID) NOT NULL,
    REPLY_TO_CODE CHAR(7) CHECK(REPLY_TO_CODE IN ('COMMENT', 'POST')),
    REPLY_TO_POST_ID INTEGER REFERENCES SOCIAL_NETWORK.POST(POST_ID) NOT NULL,
    REPLY_TO_COMMENT_ID INTEGER REFERENCES SOCIAL_NETWORK.COMMENT(COMMENT_ID),
    COMMENT_TXT TEXT NOT NULL,
    COMMENT_DTTM TIMESTAMP DEFAULT now(),
    CHECK((REPLY_TO_CODE = 'COMMENT' AND REPLY_TO_COMMENT_ID IS NOT NULL) OR
          REPLY_TO_CODE = 'POST')
);

CREATE TABLE SOCIAL_NETWORK.MESSAGE (
    MESSAGE_ID INTEGER PRIMARY KEY,
    FROM_ID INTEGER REFERENCES SOCIAL_NETWORK.USER(USER_ID) NOT NULL,
    TO_ID INTEGER REFERENCES SOCIAL_NETWORK.USER(USER_ID) NOT NULL,
    MESSAGE_TXT TEXT,
    MESSAGE_DTTM TIMESTAMP DEFAULT now()
);

CREATE TABLE SOCIAL_NETWORK.ATTACHMENT (
    ATTACHMENT_ID INTEGER PRIMARY KEY,
    ATTACH_TO_CODE CHAR(7) CHECK(ATTACH_TO_CODE IN ('MESSAGE', 'POST')),
    ATTACH_TO_POST_ID INTEGER REFERENCES SOCIAL_NETWORK.POST(POST_ID),
    ATTACH_TO_MESSAGE_ID INTEGER REFERENCES SOCIAL_NETWORK.MESSAGE(MESSAGE_ID),
    CHECK(ATTACH_TO_POST_ID IS NOT NULL OR ATTACH_TO_MESSAGE_ID IS NOT NULL),
    ATTACHMENT_TYPE_CODE VARCHAR(20) CHECK(ATTACHMENT_TYPE_CODE IN
                                           ('PHOTO', 'VIDEO', 'AUDIO', 'POST', 'FILE')),
    PATH_TO_FILE_TXT VARCHAR(255),
    ATTACHED_POST_ID INTEGER REFERENCES SOCIAL_NETWORK.POST(POST_ID),
    CHECK((ATTACH_TO_CODE = 'MESSAGE' AND ATTACH_TO_MESSAGE_ID IS NOT NULL) OR
          (ATTACH_TO_CODE = 'POST' AND ATTACH_TO_POST_ID IS NOT NULL)),
    CHECK((ATTACH_TO_CODE = 'POST' AND ATTACHED_POST_ID IS NOT NULL) OR
          (ATTACH_TO_CODE <> 'POST' AND PATH_TO_FILE_TXT IS NOT NULL))
);

CREATE TABLE SOCIAL_NETWORK.SUBSCRIPTION (
    WHO_SUBSCRIBED_ID INTEGER REFERENCES SOCIAL_NETWORK.USER(USER_ID) NOT NULL ,
    TO_WHO_SUBSCRIBED_ID INTEGER REFERENCES SOCIAL_NETWORK.USER(USER_ID) NOT NULL,
    CONSTRAINT SUBSCRIPTION_KEY PRIMARY KEY (WHO_SUBSCRIBED_ID,TO_WHO_SUBSCRIBED_ID),
    VALID_FROM_DTTM TIMESTAMP DEFAULT now(),
    VALID_TO_DTTM TIMESTAMP DEFAULT now() + interval '100 year'
);

